-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS wallet;

-- wallets: one Ethereum address per user (custodial, generated by walletd)
CREATE TABLE wallet.wallets (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL,
    address     TEXT NOT NULL,          -- 0x-prefixed checksummed EIP-55
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_wallet_user    UNIQUE (user_id),
    CONSTRAINT uq_wallet_address UNIQUE (lower(address))
);

CREATE INDEX idx_wallet_address ON wallet.wallets (lower(address));

-- transaction_log: event-sourced mint/burn history per wallet
CREATE TABLE wallet.transaction_log (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL,
    address     TEXT NOT NULL,          -- wallet address (denormalised for fast reads)
    tx_hash     TEXT NOT NULL,          -- on-chain transaction hash
    event_type  TEXT NOT NULL           -- "mint" | "burn" | "transfer_in" | "transfer_out"
                    CHECK (event_type IN ('mint','burn','transfer_in','transfer_out')),
    amount_wei  TEXT NOT NULL,          -- decimal string
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Idempotency: same on-chain tx + event type recorded only once
    CONSTRAINT uq_tx_log_hash_type UNIQUE (tx_hash, event_type)
);

CREATE INDEX idx_tx_log_user_time ON wallet.transaction_log (user_id, occurred_at DESC);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS wallet.transaction_log;
DROP TABLE IF EXISTS wallet.wallets;
DROP SCHEMA IF EXISTS wallet CASCADE;
-- +goose StatementEnd
